version: '3'
services:
  db:
    image: postgres:14.11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ethscriptions_indexer_mainnet
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/apps
    ports:
      - "4000:4000"
    depends_on:
      - db
      - memcached
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/ethscriptions_indexer_mainnet
      # DATABASE_REPLICA_URL: 
      RUN_MIGRATIONS: true

  clockwork:
    build: .
    command: bash -c "bundle exec clockwork config/main_importer_clock.rb"
    volumes:
      - .:/apps
    depends_on:
      - db
      - memcached
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/ethscriptions_indexer_mainnet
      # DATABASE_REPLICA_URL: 
      ETHEREUM_CLIENT_BASE_URL: ${ETHEREUM_CLIENT_BASE_URL}
      ETHEREUM_CLIENT_API_KEY: ${ETHEREUM_CLIENT_API_KEY}
      ETHEREUM_NETWORK: ${ETHEREUM_NETWORK}
      ETHEREUM_CLIENT_CLASS: ${ETHEREUM_CLIENT_CLASS}
      BLOCK_IMPORT_BATCH_SIZE: ${BLOCK_IMPORT_BATCH_SIZE}
      TESTNET_START_BLOCK: ${TESTNET_START_BLOCK}

  memcached:
    image: memcached
    ports:
      - "11211:11211"

volumes:
  postgres_data:
